apiVersion: v2
name: kubeclaw
description: A Helm chart for deploying Clawdbot AI agent devpods
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: Zach
    email: zacxdev@gmail.com
