{{- if include "kubeclaw.hasWorkflows" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubeclaw.fullname" . }}-workflow-exec
  namespace: {{ include "kubeclaw.namespace" . }}
  labels:
    {{- include "kubeclaw.workflowLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubeclaw.fullname" . }}-workflow-exec
subjects:
  - kind: ServiceAccount
    name: {{ include "kubeclaw.workflowSaName" . }}
    namespace: {{ include "kubeclaw.namespace" . }}
{{- end }}
