{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeclaw.fullname" . }}-devpod
  namespace: {{ include "kubeclaw.namespace" . }}
  labels:
    {{- include "kubeclaw.labels" . | nindent 4 }}
{{- end }}
